import type { NextPage } from 'next'
import Head from 'next/head'
import {app, auth, db, githubProvider} from "../firebase";
import {useEffect} from "react";
import {Button} from "@mui/material";
import {FaGithub} from "react-icons/all";
import {signInWithPopup, User} from "@firebase/auth";
import {collection, doc, getDoc, query, setDoc} from "@firebase/firestore";
import {useCollectionData} from "react-firebase-hooks/firestore";

const Home: NextPage = () => {
    console.log(auth.currentUser)

    const [users] = useCollectionData(query(collection(db,"Users")))

    const addUser = (user : User)=> {
        getDoc(doc(db,"Users",user.uid))
            .then(snapshot => {
                if(!snapshot.exists()) {
                    setDoc(doc(db,"Users",user.uid),{
                        uid: user.uid,
                        displayName: user.displayName,
                        email: user.email,
                        photoUrl: user.photoURL,
                        // @ts-ignore
                        username: user.reloadUserInfo?.screenName
                    }).catch(error=> console.error(error))
                }
            }).catch(error => console.error(error))
    }

    useEffect(()=>{
        if(auth.currentUser)
            addUser(auth.currentUser!)
    },[])

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Button
                onClick={()=>{
                    signInWithPopup(auth,githubProvider)
                        .then(result => {
                            addUser(result.user!)
                        })
                        .catch(error=> console.error(error))
                }}>
                {/*<FaGithub/>*/}
                <span>Sign in</span>
            </Button>
            <div className="w-[100%] bg-red-200">
                Leaderboard
            </div>
        </div>
    )
}

export default Home
